InMAPData= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/TR_gemmachtest/inmapData_GEMMACH_BASEGM_2015_017_10Z.nc"
#InMAPData= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/TR_gemmachtest/inmapData_GEMMACH_BASEGM_2015_017_test.nc"
VariableGridData = "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/TR_gemmachtest/vargrid_GEMMACH_BASEGM_2015_017_coarse_test.mpack.gz"

OutputFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/TR_gemmachtest/GEMMACH_BASEGM_2015_017_coarseInmapOuts.shp"
#static = true

EmissionUnits= "ug/s"
EmissionsShapefiles = [
    "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/TR_gemmachtest/Emissions/BASEGM_2015_E010_Sumlcc.shp",
]

[OutputVariables]
TotalPM25 = "PrimaryPM25 + pNH4 + pSO4 + pNO3 + SOA"
TotalPopD = "(exp(log(1.078)/10 * TotalPM25) - 1) * TotalPop * AllCause / 100000"
TotalPop = "TotalPop"
AllCause = "AllCause"
PrimPM25 = "PrimaryPM25"
PSO4 = "pSO4"
PNO3 = "pNO3"
PNH4 = "pNH4"
SOA = "SOA"
SOx = "SOx"
NH3 = "NH3"
NOx = "NOx"
BasePM25 = "BaselineTotalPM25"

[VarGrid]
GridProj= "+proj=lcc +lat_0=40 +lon_0=-96 +lat_1=50 +lat_2=70 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +to_meter=1"
#GridProj= "+proj=longlat +units=degrees"
#Xnests= [744,2,2,2,2,2,2,2]
#Ynests= [669,2,2,2,2,2,2,2]
#Xnests= [25,2] #VariableGridDx= 289674.0
#Ynests= [25,2] #VariableGridDy= 259668.0
Xnests= [5,2]
Ynests= [5,2]
VariableGridXo= -4084285.4453117 #VariableGridXo= -4184312.05377675
VariableGridYo= -1929796.221 #VariableGridYo= -2029822.82977676
#VariableGridXo= -1938548
#VariableGridYo= 1416017
#VariableGridDx= 10002.6608465054
#VariableGridDy= 10002.6608465054
HiResLayers= 1
PopDensityThreshold= 55000000.0
PopThreshold= 100000.0
PopConcThreshold= 0.000000001
#CensusFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/TR_gemmachtest/Emissions/emisspoptest_4x4.shp"
CensusFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/TR_gemmachtest/inmap_can_pop_DA_lcc.shp"
CensusPopColumns= ["TotalPop"]
PopGridColumn= "TotalPop"
#CensusFile= "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/PopData/CanadaPopulation10km2016_lcc.shp"
#CensusPopColumns= ["TOT_POP2A"]
#PopGridColumn= "TOT_POP2A"

# MortalityRateFile is the path to the shapefile containing baseline
# mortality rate data.
MortalityRateFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/testMortalityRate.shp"

# MortalityRateColumns maps the names of each input population group to the name
# of the field in MortalityRateFile that contains its respective baseline
# mortality rate, in units of deaths per year per 100,000 people. Only mortality
# rates used in output variable expressions need to be included here.
[VarGrid.MortalityRateColumns]
#allcause= "TOT_POP2A"
#AllCause="TOT_POP2A"
AllCause = "TotalPop"


[Preproc]
CTMType= "GEMMACH"
StartDate= "20190201"
EndDate= "20190301"
CtmGridXo= -1938548.5 #-4184312.05377675
CtmGridYo= 1416017.5 #-2029822.82977676
CtmGridDx= 10002.6608465054
CtmGridDy= 10002.6608465054

[Preproc.GEMMACH]
gem_out= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/[DATE]_gemmach_test.nc"
gem_geophy= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/gem_geophy_test.nc"
gem_rdps= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/rdps/[DATE]_rdpsqc_test.nc"
gemnoChemHour= true
