InMAPData= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/inmapData_GEMMACH.nc"

OutputFile= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/inmaptest_gemmach.shp"

EmissionUnits= "tons/year"

[OutputVariables]
WindSpeed= "WindSpeed"


[VarGrid]
GridProj= "+proj=lcc"


[Preproc]
CTMType= "GEMMACH"
StartDate= "20190101"
EndDate= "20190102"
CtmGridXo= -39.44722
CtmGridYo= -31.77
CtmGridDx= 0.09
CtmGridDy= 0.09

[Preproc.GEMMACH]
gem_out= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/processed/[DATE]_gemmach.nc"
gem_geophy= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/processed/gem_geophy.nc"
gem_rdps= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/processed/rdps/[DATE]_rdpsqc.nc"
gemnoChemHour= true