InMAPData= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/inmapData_GEMMACH_golden.ncf"

OutputFile= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/xxx.shp"

EmissionUnits= "tons/year"

[OutputVariables]
WindSpeed= "WindSpeed"


[VarGrid]
GridProj= "+proj=longlat +units=degrees"

[Preproc]
CTMType= "GEMMACH"

StartDate= "20190101"
EndDate= "20190102"
CtmGridXo= -2760000.0
CtmGridYo= -1332000.0
CtmGridDx= 12000.0
CtmGridDy= 12000.0

[Preproc.GEMMACH]
gem_out= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/gemmachtest_[DATE].nc"
gem_geophy = "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/gemmachtest_gem_geophy.nc"
gem_rdps = "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/rdps/rdpsqctest_[DATE].nc"