InMAPData= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/inmapData_WRFChem_golden.ncf"

OutputFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/TimSahilTest.shp"

EmissionUnits= "tons/year"

[OutputVariables]
WindSpeed= "WindSpeed"

[VarGrid]
GridProj= "+proj=lcc +lat_1=33.000000 +lat_2=45.000000 +lat_0=40.000000 +lon_0=-97.000000 +x_0=0 +y_0=0 +a=6370997.000000 +b=6370997.000000 +to_meter=1"

[Preproc]
CTMType= "WRF-Chem"

StartDate= "20050101"
EndDate= "20050103"
CtmGridXo= -2004000.0
CtmGridYo= -540000.0
CtmGridDx= 12000.0
CtmGridDy= 12000.0

[Preproc.WRFChem]
WRFOut= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/wrfout_d01_[DATE].nc"
