#InMAPData= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/inmapData_GEMMACH.nc"
InMAPData= "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Preproc/inmapData_GEMMACH_BASEGM_2015_017_complete.nc"
VariableGridData = "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/vargrid_GEMMACH_BASEGM_2015_017_coarse.mpack.gz"
static=true
creategrid=true

OutputFile= "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Outputs/20240126_InmapOuts_BAU_2020_E108_diffneg.shp"

EmissionUnits= "g/s"
EmissionsShapefiles = [
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_NH3_negarea.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_NOx_negarea.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_PM25_negarea.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_SOx_negarea.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_VOC_negarea.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_NH3_negmajor.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_NOx_negmajor.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_PM25_negmajor.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_SOx_negmajor.shp",
    "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/Emissions/Emissions_shp/Diff/split/BAU_2020_E108_VOC_negmajor.shp"
]


[OutputVariables]
TotalPM25 = "PrimaryPM25 + pNH4 + pSO4 + pNO3 + SOA"
TotalPopD = "(exp(log(1.078)/10 * TotalPM25) - 1) * TotalPop * AllCause / 100000"
TotalPop = "TotalPop"
AllCause = "AllCause"
PrimPM25 = "PrimaryPM25"
PSO4 = "pSO4"
PNO3 = "pNO3"
PNH4 = "pNH4"
SOA = "SOA"
SOx = "SOx"
NH3 = "NH3"
NOx = "NOx"
VOC = "VOC"
BasePM25 = "BaselineTotalPM25"
BaseVOC = "BaselineVOC"
BaseSOA = "BaselineSOA"
BaseNH3 = "BaselineNH3"
BasePNH4 = "BaselinePNH4"
BaseSOx = "BaselineSOx"
BasePSO4 = "BaselinePSO4"
BaseNOx = "BaselineNOx"
BasePNO3 = "BaselinePNO3"

[VarGrid]
GridProj= "+proj=lcc +lat_0=40 +lon_0=-96 +lat_1=50 +lat_2=70 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +to_meter=1"
#GridProj= "+proj=longlat +units=degrees"
#Xnests= [744,2,2,2,2,2,2,2] #VariableGridDx= 10002.6608465054
#Ynests= [669,2,2,2,2,2,2,2] #VariableGridDy= 10002.6608465054
#Xnests= [360,2,2,2,2,2,2,2] #VariableGridDx= 20000.0
#Ynests= [290,2,2,2,2,2,2,2] #VariableGridDy= 20000.0
Xnests= [180,2,2,2,2,2,2,2] VariableGridDx= 40000.0
Ynests= [145,2,2,2,2,2,2,2] VariableGridDy= 40000.0
#Xnests= [37,2,2,2,2,2,2,2] #VariableGridDx= 201134.5857
#Ynests= [33,2,2,2,2,2,2,2] #VariableGridDy= 20035.26977
#Xnests= [150,2,2,2,2,2,2,2] #VariableGridDx= 48279.0
#Ynests= [100,2,2,2,2,2,2,2] #VariableGridDy= 64917.0
#Xnests= [50,2] #VariableGridDx= 143686.24
#Ynests= [50,2] #VariableGridDy= 116200.0
#VariableGridXo= -492156.0269 
#VariableGridYo= 1270177.17
VariableGridXo= -4034312.054 #-4184312.05377675
VariableGridYo= -1529822.83 #-2029822.82977676
#VariableGridXo= -4184312.05377675 #VariableGridXo= -4084285.4453117 #
#VariableGridYo= -2029822.82977676 #VariableGridYo= -1929796.221 # 
#VariableGridDx= 48279.0
#VariableGridDy= 64917.0
HiResLayers= 8
PopDensityThreshold= 27500000.0
PopThreshold= 50000.0
#PopDensityThreshold= 55000000.0
#PopThreshold= 100000.0
#PopConcThreshold= 0.000000001
#CensusFile= "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/PopData/inmap_can_pop_DA_lcc.shp"
CensusPopColumns= ["TotalPop"]
PopGridColumn= "TotalPop"
CensusFile= "/home/tfmrodge/scratch/GEMMACH_data/data/Inmap_outputs/PopData/inmap_can_pop_DA.shp"
#CensusPopColumns= ["TOT_POP2A"]
#PopGridColumn= "TOT_POP2A"

# MortalityRateFile is the path to the shapefile containing baseline
# mortality rate data.
MortalityRateFile= "/home/tfmrodge/projects/def-agiang01/tfmrodge/InMAP_Canada/cmd/inmap/testdata/testMortalityRate.shp"

# MortalityRateColumns maps the names of each input population group to the name
# of the field in MortalityRateFile that contains its respective baseline
# mortality rate, in units of deaths per year per 100,000 people. Only mortality
# rates used in output variable expressions need to be included here.
[VarGrid.MortalityRateColumns]
#allcause= "TOT_POP2A"
#AllCause="TOT_POP2A"
AllCause = "TotalPop"

[Preproc]
CTMType= "GEMMACH"
StartDate= "20190201"
EndDate= "20190301"
CtmGridXo= -4084285.4453117 #-4084285.4453117 #-4184312.05377675
CtmGridYo= -1929796.221 #-1929796.221 #-2029822.82977676
CtmGridDx= 10002.6608465054
CtmGridDy= 10002.6608465054

[Preproc.GEMMACH]
gem_out= "/home/tfmrodge//scratch/GEMMACH_data/data/nc3/BASEGM_2015_017/[DATE]_gemmach.nc"
gem_geophy= "/home/tfmrodge//scratch/GEMMACH_data/data/nc3/GEOPHY_VF/gem_geophy.nc"
gem_rdps= "/home/tfmrodge//scratch/GEMMACH_data/data/nc3/RDPS_QC/[DATE]_rdpsqc.nc"
gemnoChemHour= true