InMAPData= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/inmapData_GEMMACH.nc"
#InMAPData= "/home/tfmrodge/projects/def-agiang01/tfmrodge/inmap_canada/InMAP_Canada/cmd/inmap/testdata/preproc/inmapData_GEMMACH_fullday.nc"

OutputFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/inmapGEMMACH_output.shp"

EmissionUnits= "tons/year"

[OutputVariables]
WindSpeed= "WindSpeed"


[VarGrid]
GridProj= "+proj=lcc"


[Preproc]
CTMType= "GEMMACH"
StartDate= "20190101"
EndDate= "20190102"
CtmGridXo= -4184312.05377675
CtmGridYo= -2029822.82977676
CtmGridDx= 10002.6608465054
CtmGridDy= 10002.6608465054

[Preproc.GEMMACH]
#gem_out= "/home/tfmrodge/scratch/GEMMACH_data/data/nc3/BASEGM_2015_017/[DATE]_gemmach.nc"
#gem_geophy= "/home/tfmrodge/scratch/GEMMACH_data/data/nc3/GEOPHY_VF/gem_geophy.nc"
#gem_rdps= "/home/tfmrodge/scratch/GEMMACH_data/data/nc3/RDPS_QC/[DATE]_rdpsqc.nc"
gem_out= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/processed/[DATE]_gemmach.nc"
gem_geophy= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/processed/gem_geophy.nc"
gem_rdps= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/processed/rdps/[DATE]_rdpsqc.nc"
gemnoChemHour= true