InMAPData= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/inmapData_GEMMACH_golden.nc"

OutputFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/inmaptest_gemmach.shp"

EmissionsShapefiles = "/workspaces/InMAP_Canada/cmd/inmap/testdata/testemiss_gemmach.shp"
EmissionUnits= "tons/year"

VariableGridData = "/workspaces/InMAP_Canada/cmd/inmap/testdata/inmapVarGrid.gob"

[OutputVariables]
WindSpeed= "WindSpeed"

[VarGrid]
GridProj= "+proj=lcc +lat_0=40 +lon_0=-96 +lat_1=50 +lat_2=70 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"
#GridProj= "+proj=longlat +units=degrees"
Xnests= [8,2, 2, 2]
Ynests= [8,2, 2, 2]
CtmGridXo= -4184312.05377675
CtmGridYo= -2029822.82977676
CtmGridDx= 1860494.917
CtmGridDy= 1672945.027
HiResLayers= 1
PopDensityThreshold= 0.001
PopThreshold= 25000.0
PopConcThreshold= 0.00000000001
CensusFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/gemmach_poptest_2016/poptest2016_lcc.shp"
CensusPopColumns= ["TOT_POP2A_"]
PopGridColumn= "TOT_POP2A_"

# MortalityRateFile is the path to the shapefile containing baseline
# mortality rate data.
#MortalityRateFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/gemmach_poptest_2016/poptest2016_lcc.shp"
MortalityRateFile= "/workspaces/InMAP_Canada/cmd/inmap/testdata/testMortalityRate.shp"

# MortalityRateColumns maps the names of each input population group to the name
# of the field in MortalityRateFile that contains its respective baseline
# mortality rate, in units of deaths per year per 100,000 people. Only mortality
# rates used in output variable expressions need to be included here.
[VarGrid.MortalityRateColumns]
#allcause= "TOT_POP2A_"
AllCause = "TOT_POP2A_"

[Preproc]
CTMType= "GEMMACH"
StartDate= "20190101"
EndDate= "20190102"
CtmGridXo= -4184312.05377675
CtmGridYo= -2029822.82977676
CtmGridDx= 1860494.917
CtmGridDy= 1672945.027

[Preproc.GEMMACH]
gem_out= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/[DATE]_gemmach_test.nc"
gem_geophy= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/gem_geophy_test.nc"
gem_rdps= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/rdps/[DATE]_rdpsqc_test.nc"
#gem_out= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/[DATE]_gemmach_test.nc"
#gem_geophy= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/gem_geophy_test.nc"
#gem_rdps= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/rdps/[DATE]_rdpsqc_test.nc"
gemnoChemHour= true