InMAPData= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/inmapData_GEMMACH.nc"

OutputFile= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/inmaptest_gemmach.shp"

EmissionUnits= "tons/year"

[OutputVariables]
WindSpeed= "WindSpeed"


[VarGrid]
#GridProj= "+proj=ob_tran +o_proj=longlat +o_lon_p=87.597031302933 +o_lat_p=31.7583124544932 +lon_0=180 +a=6370997 +units=degrees +no_defs"
GridProj= "+proj=longlat"


[Preproc]
CTMType= "GEMMACH"
StartDate= "20190101"
EndDate= "20190102"
CtmGridXo= -39.44722
CtmGridYo= -31.77
CtmGridDx= 13.05
CtmGridDy= 16.382

[Preproc.GEMMACH]
gem_out= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/[DATE]_gemmach_test.nc"
gem_geophy= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/gem_geophy_test.nc"
gem_rdps= "/workspaces/InMAP_Canada/cmd/inmap/testdata/preproc/gemmach/rdps/[DATE]_rdpsqc_test.nc"
#gem_out= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/[DATE]_gemmach_test.nc"
#gem_geophy= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/gem_geophy_test.nc"
#gem_rdps= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/gemmach/rdps/[DATE]_rdpsqc_test.nc"
gemnoChemHour= true