InMAPData= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/inmapData_GEMMACH.nc"

OutputFile= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/preproc/inmaptest_gemmach.shp"

EmissionUnits= "tons/year"

[OutputVariables]
WindSpeed= "WindSpeed"


[VarGrid]
GridProj= "+proj=lcc"


[Preproc]
CTMType= "GEMMACH"
StartDate= "20190101"
EndDate= "20190102"
CtmGridXo= -39.44722
CtmGridYo= -31.77
CtmGridDx= 0.09
CtmGridDy= 0.09

[Preproc.GEMMACH]
gem_out= "/home/tfmrodge/scratch/GEMMACH_data/data/nc3/[DATE]_gemmach.nc"
gem_geophy= "/home/tfmrodge/scratch/GEMMACH_data/data/nc3/GEOPHY_VF/gem_geophy_1.nc"
gem_rdps= "/home/tfmrodge/scratch/GEMMACH_data/data/nc3/[DATE]_rdpsqc.nc"
gemnoChemHourIndex= true